#!/usr/bin/env python3
"""
从 ODA 规约生成 C stub 代码

用法:
    python gen_oda_stub.py pathisrelativew.json -o ../klee/oda_stubs.c
"""

import json
import re
import argparse
from pathlib import Path
from typing import Dict, List, Optional


class ODAStubGenerator:
    """ODA stub 代码生成器"""
    
    def __init__(self, spec_path: str):
        with open(spec_path, 'r', encoding='utf-8') as f:
            self.spec = json.load(f)
    
    def generate(self) -> str:
        """生成完整的 stub 代码"""
        code_parts = []
        
        # 头部注释
        code_parts.append(self._generate_header())
        
        # 包含文件
        code_parts.append(self._generate_includes())
        
        # 获取目标函数名
        target_func = self.spec.get("target_function", "")
        
        # 为每个依赖函数生成 stub
        for dep in self.spec.get("dependencies", []):
            name = dep["name"]
            
            # 跳过目标函数本身（避免重复定义）
            if name == target_func:
                print(f"  跳过目标函数 {name}（避免重复定义）")
                continue
            
            code_parts.append(self._generate_stub(dep))
        
        return '\n\n'.join(code_parts)
    
    def _generate_header(self) -> str:
        """生成文件头部注释"""
        target = self.spec["target_function"]
        desc = self.spec.get("description", "")
        
        return f"""/*
 * Auto-generated ODA stubs for {target}
 * 
 * {desc}
 * 
 * This file contains simplified implementations (stubs) of external
 * functions that {target} depends on. These stubs use symbolic
 * execution to explore all possible behaviors without implementing
 * the full logic.
 * 
 * Generated by gen_oda_stub.py
 */"""
    
    def _generate_includes(self) -> str:
        """生成包含文件"""
        return """#include <klee/klee.h>
#include <stddef.h>
#include <wchar.h>

// Windows types (for KLEE environment)
#ifndef _WINDOWS_
typedef unsigned short WCHAR;
typedef const WCHAR *LPCWSTR;
typedef WCHAR *LPWSTR;
typedef int BOOL;
typedef unsigned long DWORD;
#define TRUE 1
#define FALSE 0
#define NULL ((void*)0)
#endif"""
    
    def _generate_stub(self, dep: Dict) -> str:
        """为单个依赖函数生成 stub"""
        name = dep["name"]
        signature = dep["signature"]
        desc = dep.get("description", "")
        # 避免描述中嵌套注释导致 C 注释块破坏
        desc = desc.replace("/*", "").replace("*/", "")
        abstraction = dep["abstraction"]
        reason = abstraction.get("reason", "")
        constraints = abstraction["constraints"]

        # 宏/内联 helper：直接输出 #define，避免函数签名解析
        if dep.get("kind") == "macro":
            macro_body = f"#define {name}(arr) (sizeof(arr) / sizeof((arr)[0]))"
            return f"// Macro stub for {name}\n{macro_body}"
        
        # 跳过无效的函数（如 __exception_copy_ctor）
        if name.startswith("__") or "this" in signature or "&" in signature.split('(')[0]:
            print(f"  跳过无效函数 {name}（签名无效）")
            return f"// Skipped: {name} (invalid signature)"
        
        # 提取返回类型和参数
        try:
            return_type, func_decl = self._parse_signature(signature)
        except Exception as e:
            print(f"  跳过函数 {name}（解析失败: {e}）")
            return f"// Skipped: {name} (parse error: {e})"
        
        # 生成注释
        comment = f"""/*
 * Stub for {name}
 * 
 * {desc}
 * 
 * Abstraction strategy: {abstraction['type']}
 * Reason: {reason}
 */"""
        
        # 生成函数体
        body_lines = []
        has_return_stmt = False
        ret_var: Optional[str] = None
        for constraint in constraints:
            # 清理约束代码
            line = constraint.strip()

            # 规范 klee_make_symbolic：统一重写为双引号字符串 name，避免多字符常量
            if "klee_make_symbolic" in line:
                m = re.search(r"klee_make_symbolic\(&([A-Za-z_][A-Za-z0-9_]*)", line)
                sym_var = m.group(1) if m else "sym"
                sym_name = f"{name}_ret"
                line = f'klee_make_symbolic(&{sym_var}, sizeof({sym_var}), "{sym_name}");'
                ret_var = ret_var or sym_var
            
            # 跳过空行
            if not line:
                body_lines.append("")
                continue
            
            # 对包含字符常量的行统一转义反斜杠，避免 `'\'` 变成未闭合字符常量
            if "\\" in line:
                line = line.replace("'\\'", "'\\\\'")
                line = line.replace("\\", "\\\\")

            # 如果行不以分号结尾，且不是以 { 或 } 结尾，添加分号
            if not line.endswith((';', '{', '}')):
                line = line + ';'

            if line.startswith("return"):
                has_return_stmt = True

            body_lines.append(f"    {line}")

        # 非 void 返回值兜底：如果没有显式 return，则追加安全的默认返回
        needs_return = return_type.strip() != "void"
        if needs_return and not has_return_stmt:
            if ret_var:
                body_lines.append(f"    return {ret_var};")
            elif '*' in return_type:
                body_lines.append("    return NULL;")
            else:
                body_lines.append("    return 0;")
        
        body = '\n'.join(body_lines)
        
        # 组合完整函数
        return f"""{comment}
{return_type} {name}{func_decl} {{
{body}
}}"""
    
    def _parse_signature(self, signature: str) -> tuple:
        """
        解析函数签名
        
        Args:
            signature: "int WINAPI lstrlenW(LPCWSTR lpString)"
        
        Returns:
            ("int", "(LPCWSTR lpString)")
        """
        # 移除 WINAPI, CDECL 等调用约定
        signature = signature.replace("WINAPI", "").replace("CDECL", "")
        signature = signature.replace("__cdecl", "").replace("__stdcall", "")
        
        # 修复常见的类型名称
        signature = signature.replace("VOID", "void")
        signature = signature.replace("INT", "int")
        
        # 检查是否是无效的签名（如 "return xxx(...)"）
        if signature.strip().startswith("return "):
            # 这是一个无效的签名，尝试提取函数名
            # "return __exception_copy_ctor(this, rhs, &range_error_vtable)"
            # 提取函数名和参数
            match = signature.strip()[7:]  # 移除 "return "
            paren_pos = match.find('(')
            if paren_pos > 0:
                func_name = match[:paren_pos].strip()
                params = match[paren_pos:]
                # 假设返回 void
                return "void", params
            else:
                # 无法解析，返回默认值
                return "void", "()"
        
        # 找到函数名的位置（第一个 '(' 之前）
        paren_pos = signature.find('(')
        if paren_pos == -1:
            raise ValueError(f"Invalid signature: {signature}")
        
        # 提取返回类型和参数部分
        before_paren = signature[:paren_pos].strip()
        params = signature[paren_pos:]
        
        # 返回类型是最后一个空格之前的部分
        parts = before_paren.split()
        if len(parts) < 2:
            # 只有函数名，没有返回类型，假设为 void
            return "void", params
        
        return_type = ' '.join(parts[:-1])  # 所有部分除了函数名
        
        return return_type, params
    
    def generate_test_harness_template(self) -> str:
        """生成 KLEE 测试驱动程序模板"""
        target = self.spec["target_function"]
        inputs = self.spec.get("test_inputs", {})
        symbolic_vars = inputs.get("symbolic_vars", [])
        
        code_parts = []
        
        # 头部
        code_parts.append(f"""/*
 * KLEE test harness for {target}
 * 
 * This program creates symbolic inputs and calls {target}
 * to explore all possible execution paths.
 */

#include <klee/klee.h>
#include "oda_stubs.c"

// Forward declaration of target function
// TODO: Add actual signature
// BOOL {target}(LPCWSTR path);

int main() {{""")
        
        # 创建符号变量
        for var in symbolic_vars:
            var_name = var["name"]
            var_type = var["type"]
            desc = var.get("description", "")
            
            code_parts.append(f"""
    // {desc}
    {var_type} {var_name};
    klee_make_symbolic(&{var_name}, sizeof({var_name}), "{var_name}");""")
        
        # 调用目标函数
        code_parts.append(f"""
    // Call target function
    // TODO: Adjust parameters
    // BOOL result = {target}(path);
    
    return 0;
}}""")
        
        return '\n'.join(code_parts)


def main():
    parser = argparse.ArgumentParser(description="生成 ODA stub 代码")
    parser.add_argument("spec", help="ODA 规约文件 (JSON)")
    parser.add_argument("-o", "--output", help="输出文件路径")
    parser.add_argument("--template", action="store_true", 
                       help="同时生成测试驱动程序模板")
    
    args = parser.parse_args()
    
    generator = ODAStubGenerator(args.spec)
    
    # 生成 stub 代码
    stub_code = generator.generate()
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(stub_code)
        print(f"Stub 代码已生成: {args.output}")
    else:
        print(stub_code)
    
    # 生成测试驱动程序模板
    if args.template:
        template_code = generator.generate_test_harness_template()
        template_path = Path(args.output).parent / "harness_template.c"
        
        with open(template_path, 'w', encoding='utf-8') as f:
            f.write(template_code)
        print(f"测试驱动程序模板已生成: {template_path}")


if __name__ == "__main__":
    main()
